require 'nokogiri'
require 'open-uri'
require 'pry'

require_relative '../lib/meal'
require_relative '../lib/scraper'
require_relative '../lib/cart'
require_relative '../lib/plot'
require_relative '../lib/menu'
require_relative '../lib/orders'